# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stack Blog
email: stack-blog@inria.fr
description: "Software -  <a href='http://stack.inria.fr'>Stack</a> — for Massively Geo-Distributed Infrastructures"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://stack.inria.fr/blog/" # the base hostname & protocol for your site
twitter_username: software_stack_
repository: "Stack/blog"
#github_username:

# Build settings
markdown: kramdown

